import PDFDocument from "pdfkit";

export type InvoiceData = {
  invoiceNumber: string;
  braiderName: string;
  clientName: string;
  serviceName: string;
  appointmentDate: string;
  amountPence: number;
  utrMasked: string | null;
};

/** PRD Step 4: "Invoice generator built into platform (PDF download)". One
 * plain template — this is a utility document, not a branded artifact, so
 * it doesn't need a design pass. */
export function generateInvoicePdf(data: InvoiceData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).text("Invoice", { align: "right" });
    doc.fontSize(10).text(`Invoice #${data.invoiceNumber}`, { align: "right" });
    doc.moveDown(2);

    doc.fontSize(12).text(data.braiderName);
    if (data.utrMasked) doc.fontSize(9).fillColor("#666").text(`UTR: ${data.utrMasked}`);
    doc.fillColor("#000").moveDown();

    doc.fontSize(11).text(`Billed to: ${data.clientName}`);
    doc.text(`Date of service: ${data.appointmentDate}`);
    doc.moveDown();

    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.5);

    doc.fontSize(11).text(data.serviceName, 50, doc.y, { continued: true });
    doc.text(`£${(data.amountPence / 100).toFixed(2)}`, { align: "right" });
    doc.moveDown();

    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.5);

    doc.fontSize(12).text("Total", 50, doc.y, { continued: true });
    doc.text(`£${(data.amountPence / 100).toFixed(2)}`, { align: "right" });

    doc.moveDown(3);
    doc
      .fontSize(8)
      .fillColor("#666")
      .text("Generated by Braidr. This invoice is provided as a record of services rendered.");

    doc.end();
  });
}
